container:
  image: "registry.gitlab.com/tigefa/ffmpeg"
  cpu: 8
  memory: 21

ffmpeg_task:
  timeout_in: 120m
  install_script:
    - apt-get update
    - apt-get dist-upgrade -yqq
    - apt-get install -yqq sudo lsb-base lsb-release apt-transport-https ca-certificates software-properties-common wget curl netcat aria2 whois figlet p7zip p7zip-full zip unzip
    - apt-get install -yqq wget aria2 ffmpeg telnet tree
  test_script:
    - aria2c "https://www.dropbox.com/s/dl/ltqsrbqn32hon03/HTnNJ.mp4"
#    - "aria2c --check-certificate=false --header 'Host: fr15.seedr.cc' --user-agent 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:80.0) Gecko/20100101 Firefox/80.0' --header 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8' --header 'Accept-Language: id,en-US;q=0.7,en;q=0.3' --referer 'https://www.seedr.cc/files/143224606' --header 'Upgrade-Insecure-Requests: 1' 'https://fr15.seedr.cc/ff_get/745654342/The.Swindlers.2017.1080p.BluRay.x264-[YTS.AM].mp4?st=byj-m1kT0o0T5ALB0-WhcA&e=1600281470' --out 'The.Swindlers.2017.1080p.BluRay.x264-[YTS.AM].mp4'"
    - ffmpeg -i "HTnNJ.mp4" -threads 16 -c:v libx265 -c:a aac -metadata title="Hitomi Tanaka And Nadine J" -preset veryfast HTnNJ.x265.mp4
    - ls -hal
  binaries_artifacts:
    path: "HTnNJ.x265.mp4"
