container:
  image: "registry.gitlab.com/tigefa/ffmpeg"
  cpu: 8
  memory: 21

ffmpeg_task:
  timeout_in: 120m
  install_script:
    - apt-get update
    - apt-get dist-upgrade -yqq
    - apt-get install -yqq sudo lsb-base lsb-release apt-transport-https ca-certificates software-properties-common wget curl netcat aria2 whois figlet p7zip p7zip-full zip unzip
    - apt-get install -yqq wget aria2 ffmpeg telnet tree
  test_script:
    - "aria2c --check-certificate=false --min-split-size=100M --max-concurrent-downloads=16 --max-connection-per-server=16 https://www.dropbox.com/s/dl/c77wo8wjaom1hlw/The.Conjuring.2.2016.1080p.BluRay.x264-%5BYTS.AG%5D.mp4"
    - ffmpeg -i "The.Conjuring.2.2016.1080p.BluRay.x264-[YTS.AG].mp4" -threads 16 -c:v libx265 -c:a copy -metadata title="The Conjuring 2 2016" -preset veryfast The.Conjuring.2.2016.1080p.BluRay.x265.mp4
    - ls -hal
  binaries_artifacts:
    path: "The.Conjuring.2.2016.1080p.BluRay.x265.mp4"
