container:
  image: "registry.gitlab.com/tigefa/ffmpeg"
  cpu: 8
  memory: 21

ffmpeg_task:
  timeout_in: 120m
  install_script:
    - apt-get update
    - apt-get dist-upgrade -yqq
    - apt-get install -yqq sudo lsb-base lsb-release apt-transport-https ca-certificates software-properties-common wget curl netcat aria2 whois figlet p7zip p7zip-full zip unzip
    - apt-get install -yqq wget aria2 ffmpeg telnet tree
  test_script:
    - aria2c --bt-seed-unverified=true --seed-time=1 --seed-ratio=1.0 "https://onejav.com/torrent/venu972/download/221815/onejav.com_venu972.torrent"
#    - "aria2c --check-certificate=false --header 'Host: nl25.seedr.cc' --user-agent 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:81.0) Gecko/20100101 Firefox/81.0' --header 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8' --header 'Accept-Language: id,en-US;q=0.7,en;q=0.3' --referer 'https://www.seedr.cc/files/146856754' --header 'Upgrade-Insecure-Requests: 1' 'https://nl25.seedr.cc/ff_get/768930187/Air.Doll.2009.1080p.BluRay.x264-[YTS.AM].mp4?st=Dc-LGfT5L7qU7EdcHEJX3Q&e=1603217075' --out 'Air.Doll.2009.1080p.BluRay.x264-[YTS.AM].mp4'"
    - ffmpeg -i "VENU-972.mp4" -threads 16 -c:v libx265 -c:a aac -metadata title="Nene Tanaka" -preset veryfast VENU-972.x265.mp4
    - ls -hal
  binaries_artifacts:
    path: "VENU-972.x265.mp4"
