container:
  image: "registry.gitlab.com/tigefa/ffmpeg"
  cpu: 16
  memory: 32

ffmpeg_task:
  timeout_in: 120m
  requirements_script:
    - apt-get update
    - apt-get dist-upgrade -yqq
    - apt-get install -yqq sudo lsb-base lsb-release apt-transport-https ca-certificates software-properties-common wget curl netcat aria2 whois figlet p7zip p7zip-full zip unzip
    - apt-get install -yqq wget aria2 ffmpeg telnet tree
  downloading_script:
    - "aria2c --check-certificate=false --min-split-size=100M --max-concurrent-downloads=16 --max-connection-per-server=16 https://www.dropbox.com/s/dl/ya0kfgwjkxc0wde/rkprime.21.02.24.codi.vore.sweeping.up.with.her.big.natural.tits.mp4"
  rendering_script:
    - ffmpeg -i "rkprime.21.02.24.codi.vore.sweeping.up.with.her.big.natural.tits.mp4" -threads 16 -c:v libx265 -c:a copy -metadata title="Codi Vore - Sweeping Up With Her Big Natural Tits" -preset veryfast -pix_fmt yuv420p10le codi.vore.sweeping.up.with.her.big.natural.tits.x265.mp4
    - ls -hal
  binaries_artifacts:
    path: "codi.vore.sweeping.up.with.her.big.natural.tits.x265.mp4"
