container:
  image: "registry.gitlab.com/tigefa/ffmpeg"
  cpu: 16
  memory: 32

ffmpeg_task:
  timeout_in: 120m
  requirements_script:
    - apt-get update
    - apt-get dist-upgrade -yqq
    - apt-get install -yqq sudo lsb-base lsb-release apt-transport-https ca-certificates software-properties-common wget curl netcat aria2 whois figlet p7zip p7zip-full zip unzip
    - apt-get install -yqq wget aria2 ffmpeg telnet tree
  downloading_script:
    - "aria2c --check-certificate=false --min-split-size=100M --max-concurrent-downloads=16 --max-connection-per-server=16 --header 'Host: nl36.seedr.cc' --user-agent 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:86.0) Gecko/20100101 Firefox/86.0' --header 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8' --header 'Accept-Language: id,en-US;q=0.7,en;q=0.3' --referer 'https://www.seedr.cc/files/162379547' --header 'Upgrade-Insecure-Requests: 1' 'https://nl36.seedr.cc/ff_get/862324478/milfty.21.02.28.melanie.hicks.payback.for.stepmom.mp4?st=CkR0Np-bErFee8txdioHGw&e=1614970401' --out 'milfty.21.02.28.melanie.hicks.payback.for.stepmom.mp4'"
  rendering_script:
    - ffmpeg -i "milfty.21.02.28.melanie.hicks.payback.for.stepmom.mp4" -threads 16 -c:v libx265 -c:a copy -metadata title="Milfty - Melanie Hicks - Payback For Stepmom" -preset veryfast -pix_fmt yuv420p10le milfty.melanie.hicks.payback.for.stepmom.x265.mp4
    - ls -hal
  binaries_artifacts:
    path: "milfty.melanie.hicks.payback.for.stepmom.x265.mp4"
