container:
  image: "registry.gitlab.com/tigefa/ffmpeg"
  cpu: 8
  memory: 21

ffmpeg_task:
  timeout_in: 120m
  install_script:
    - apt-get update
    - apt-get dist-upgrade -yqq
    - apt-get install -yqq sudo lsb-base lsb-release apt-transport-https ca-certificates software-properties-common wget curl netcat aria2 whois figlet p7zip p7zip-full zip unzip
    - apt-get install -yqq wget aria2 ffmpeg telnet tree lshw
  test_script:
    - aria2c --bt-seed-unverified=true --seed-time=1 --seed-ratio=1.0 "https://onejav.com/torrent/miaa311/download/966580/onejav.com_miaa311.torrent"
#    - "aria2c --check-certificate=false 'http://103.126.226.135:8080/download/NewSensatins.20.06.05.Dylann.Vox..480p.MP4-XXX/newsensations.20.06.05.dylann.vox.mp4'"
    - ffmpeg -i "MIAA-311.mp4" -threads 16 -c:v libx265 -c:a aac -metadata title="Nene Tanaka" -preset veryfast -s 960x540 MIAA-311.x265.mp4
    - ls -hal
  binaries_artifacts:
    path: "MIAA-311.x265.mp4"
