container:
  image: "registry.gitlab.com/tigefa/ffmpeg"
  cpu: 8
  memory: 21

ffmpeg_task:
  timeout_in: 120m
  requirements_script:
    - apt-get update
    - apt-get dist-upgrade -yqq
    - apt-get install -yqq sudo lsb-base lsb-release apt-transport-https ca-certificates software-properties-common wget curl netcat aria2 whois figlet p7zip p7zip-full zip unzip
    - apt-get install -yqq wget aria2 ffmpeg telnet tree
  downloading_script:
    - "aria2c --check-certificate=false --min-split-size=100M --max-concurrent-downloads=16 --max-connection-per-server=16 https://www.dropbox.com/s/dl/ad1n6siyel2asp0/L.U.C.A.The.Beginning.E05.210215.720p-NEXT.mp4"
  rendering_script:
    - ffmpeg -i "L.U.C.A.The.Beginning.E05.210215.720p-NEXT.mp4" -threads 16 -c:v libx265 -c:a copy -metadata title="L.U.C.A The Beginning Episode 05" -preset veryfast 05.mkv
    - ls -hal
  binaries_artifacts:
    path: "05.mkv"
