container:
  image: "registry.gitlab.com/tigefa/ffmpeg"
  cpu: 8
  memory: 16

ffmpeg_task:
  timeout_in: 120m
  requirements_script:
    - apt-get update
    - apt-get dist-upgrade -yqq
    - apt-get install -yqq sudo lsb-base lsb-release apt-transport-https ca-certificates software-properties-common wget curl netcat aria2 whois figlet p7zip p7zip-full zip unzip
    - apt-get install -yqq wget aria2 ffmpeg telnet tree
  downloading_script:
    - "aria2c --check-certificate=false --min-split-size=100M --max-concurrent-downloads=16 --max-connection-per-server=16 https://www.dropbox.com/s/dl/25z65js0ezgthv0/Godzilla.vs.Kong.2021.720p.HMAX.WEB-DL.DDP5.1.x264-MRCS.mkv"
  rendering_script:
    - ffmpeg -i "Godzilla.vs.Kong.2021.720p.HMAX.WEB-DL.DDP5.1.x264-MRCS.mkv" -threads 16 -c:v libx265 -c:a copy -metadata title="Godzilla vs Kong 2021" -preset veryfast -pix_fmt yuv420p10le Godzilla.vs.Kong.2021.720p.WEB-DL.x265.mkv
    - ls -hal
  binaries_artifacts:
    path: "Godzilla.vs.Kong.2021.720p.WEB-DL.x265.mkv"
