container:
  image: "registry.gitlab.com/tigefa/ffmpeg"
  cpu: 8
  memory: 21

ffmpeg_task:
  timeout_in: 120m
  requirements_script:
    - apt-get update
    - apt-get dist-upgrade -yqq
    - apt-get install -yqq sudo lsb-base lsb-release apt-transport-https ca-certificates software-properties-common wget curl netcat aria2 whois figlet p7zip p7zip-full zip unzip
    - apt-get install -yqq wget aria2 ffmpeg telnet tree
  downloading_script:
    - "aria2c --check-certificate=false --min-split-size=100M --max-concurrent-downloads=16 --max-connection-per-server=16 https://www.dropbox.com/s/dl/1jkvxw7wohoi4bu/The.Nun.2018.1080p.BluRay.x264-%5BYTS.AM%5D.mp4"
  rendering_script:
    - ffmpeg -i "The.Nun.2018.1080p.BluRay.x264-[YTS.AM].mp4" -threads 16 -c:v libx265 -c:a copy -metadata title="The Nun 2018" -preset veryfast The.Nun.2018.1080p.BluRay.x265.mp4
    - ls -hal
  binaries_artifacts:
    path: "The.Nun.2018.1080p.BluRay.x265.mp4"
