container:
  image: "registry.gitlab.com/tigefa/ffmpeg"
  cpu: 16
  memory: 32

ffmpeg_task:
  timeout_in: 120m
  requirements_script:
    - apt-get update
    - apt-get dist-upgrade -yqq
    - apt-get install -yqq sudo lsb-base lsb-release apt-transport-https ca-certificates software-properties-common wget curl netcat aria2 whois figlet p7zip p7zip-full zip unzip
    - apt-get install -yqq wget aria2 ffmpeg telnet tree
  downloading_script:
    - "aria2c --check-certificate=false --min-split-size=100M --max-concurrent-downloads=16 --max-connection-per-server=16 https://www.dropbox.com/s/dl/8ouc34kho1l6n7i/L.U.C.A.The.Beginning.E08.210223.720p-NEXT.mp4"
  rendering_script:
    - ffmpeg -i "L.U.C.A.The.Beginning.E08.210223.720p-NEXT.mp4" -threads 16 -c:v libx265 -c:a copy -metadata title="L.U.C.A The Beginning Episode 08" -preset veryfast -pix_fmt yuv420p10le 08.mkv
    - ls -hal
  binaries_artifacts:
    path: "08.mkv"
