container:
  image: "registry.gitlab.com/tigefa/ffmpeg"
  cpu: 8
  memory: 16

ffmpeg_task:
  timeout_in: 120m
  requirements_script:
    - apt-get update
    - apt-get dist-upgrade -yqq
    - apt-get install -yqq sudo lsb-base lsb-release apt-transport-https ca-certificates software-properties-common wget curl netcat aria2 whois figlet p7zip p7zip-full zip unzip
    - apt-get install -yqq wget aria2 ffmpeg telnet tree
  downloading_script:
    - "aria2c --check-certificate=false --min-split-size=100M --max-concurrent-downloads=16 --max-connection-per-server=16 aria2c --header 'Host: nl30.seedr.cc' --user-agent 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:87.0) Gecko/20100101 Firefox/87.0' --header 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8' --header 'Accept-Language: id,en-US;q=0.7,en;q=0.3' --referer 'https://www.seedr.cc/' --header 'Upgrade-Insecure-Requests: 1' 'https://nl30.seedr.cc/ff_get/883105422/Sisyphus.The.Myth.S01E14.1080p.NF.WEB-DL.DDP2.0.x264-Imagine.mkv?st=R9qoT-shSTBK9Kwty_l3Eg&e=1617383654' --out 'Sisyphus.The.Myth.S01E14.1080p.NF.WEB-DL.DDP2.0.x264-Imagine.mkv'"
  rendering_script:
    - ffmpeg -i "Sisyphus.The.Myth.S01E14.1080p.NF.WEB-DL.DDP2.0.x264-Imagine.mkv" -threads 16 -c:v libx265 -c:a copy -metadata title="Sisyphus The Myth Episode 14" -preset veryfast -pix_fmt yuv420p10le -s 1280x720 14.mkv
    - ls -hal
  binaries_artifacts:
    path: "14.mkv"
