container:
  image: "registry.gitlab.com/tigefa/ffmpeg"
  cpu: 8
  memory: 21

ffmpeg_task:
  timeout_in: 120m
  install_script:
    - apt-get update
    - apt-get dist-upgrade -yqq
    - apt-get install -yqq sudo lsb-base lsb-release apt-transport-https ca-certificates software-properties-common wget curl netcat aria2 whois figlet p7zip p7zip-full zip unzip
    - apt-get install -yqq wget aria2 ffmpeg telnet tree
  test_script:
    - "aria2c --check-certificate=false --min-split-size=100M --max-concurrent-downloads=16 --max-connection-per-server=16 https://www.dropbox.com/s/dl/isr35dv88xbl003/Mr.Queen.E20.END.210214.720p-NEXT.mp4"
    - ffmpeg -i "Mr.Queen.E20.END.210214.720p-NEXT.mp4" -threads 16 -c:v libx265 -c:a copy -metadata title="Mr. Queen Episode 20" -preset veryfast 20.mkv
    - ls -hal
  binaries_artifacts:
    path: "20.mkv"
