container:
  image: "registry.gitlab.com/tigefa/ffmpeg"
  cpu: 8
  memory: 21

ffmpeg_task:
  timeout_in: 120m
  install_script:
    - apt-get update
    - apt-get dist-upgrade -yqq
    - apt-get install -yqq sudo lsb-base lsb-release apt-transport-https ca-certificates software-properties-common wget curl netcat aria2 whois figlet p7zip p7zip-full zip unzip
    - apt-get install -yqq wget aria2 ffmpeg telnet tree lshw
  test_script:
    - aria2c --bt-seed-unverified=true --seed-time=1 --seed-ratio=1.0 "https://yts.mx/torrent/download/38F85FF2FE86C7B6EDC209DF97B18744FE0E89AA"
#    - "aria2c --check-certificate=false --header 'Host: nl32.seedr.cc' --user-agent 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:80.0) Gecko/20100101 Firefox/80.0' --header 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8' --header 'Accept-Language: id,en-US;q=0.7,en;q=0.3' --referer 'https://www.seedr.cc/files/143442955' --header 'Upgrade-Insecure-Requests: 1' 'https://nl32.seedr.cc/ff_get/746982328/Inside.Men.2015.720p.BluRay.x264.AAC-[YTS.MX].mp4?st=79FjrlZ1JtThyzd-KqvDcQ&e=1600455387' --out 'Inside.Men.2015.720p.BluRay.x264.AAC-[YTS.MX].mp4'"
    - ffmpeg -i "Batman V Superman Dawn Of Justice (2016) [YTS.AG]/True.Fiction.2018.720p.WEBRip.x264.AAC-[YTS.MX].mp4" -threads 16 -c:v libx265 -c:a aac -metadata title="Batman V Superman Dawn Of Justice 2016" -preset veryfast Batman.V.Superman.Dawn.Of.Justice.2016.720p.BluRay.x265.mp4
    - ls -hal
  binaries_artifacts:
    path: "Batman.V.Superman.Dawn.Of.Justice.2016.720p.BluRay.x265.mp4"
