container:
  image: "registry.gitlab.com/tigefa/ffmpeg"
  cpu: 8
  memory: 21

ffmpeg_task:
  timeout_in: 120m
  install_script:
    - apt-get update
    - apt-get dist-upgrade -yqq
    - apt-get install -yqq sudo lsb-base lsb-release apt-transport-https ca-certificates software-properties-common wget curl netcat aria2 whois figlet p7zip p7zip-full zip unzip
    - apt-get install -yqq wget aria2 ffmpeg telnet tree
  test_script:
    - "aria2c --check-certificate=false --min-split-size=100M --max-concurrent-downloads=16 --max-connection-per-server=16 'https://www.dropbox.com/s/dl/f377a8qhbq39hyn/OFJE-288.mp4'"
    - ffmpeg -i "OFJE-288.mp4" -threads 16 -c:v libx265 -c:a copy -metadata title="Anzai Rara 2nd BEST" -preset veryfast OFJE-288.x265.mp4
    - ls -hal
  binaries_artifacts:
    path: "OFJE-288.x265.mp4"
