container:
  image: "registry.gitlab.com/tigefa/ffmpeg"
  cpu: 16
  memory: 32

ffmpeg_task:
  timeout_in: 120m
  requirements_script:
    - apt-get update
    - apt-get dist-upgrade -yqq
    - apt-get install -yqq sudo lsb-base lsb-release apt-transport-https ca-certificates software-properties-common wget curl netcat aria2 whois figlet p7zip p7zip-full zip unzip
    - apt-get install -yqq wget aria2 ffmpeg telnet tree
  downloading_script:
    - "aria2c --check-certificate=false --min-split-size=100M --max-concurrent-downloads=16 --max-connection-per-server=16 --header 'Host: fr6.seedr.cc' --user-agent 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:86.0) Gecko/20100101 Firefox/86.0' --header 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8' --header 'Accept-Language: id,en-US;q=0.7,en;q=0.3' --referer 'https://www.seedr.cc/files/163484967' --header 'Upgrade-Insecure-Requests: 1' 'https://fr6.seedr.cc/ff_get/868943622/SNIS-918.mp4?st=h5khPlddF8Ss4NbtPIEjWw&e=1615774659' --out 'SNIS-918.mp4'"
  rendering_script:
    - ffmpeg -i "SNIS-918.mp4" -threads 16 -c:v libx265 -c:a copy -metadata title="RiON" -preset veryfast -pix_fmt yuv420p10le SNIS-918.x265.mp4
    - ls -hal
  binaries_artifacts:
    path: "SNIS-918.x265.mp4"
