container:
  image: "registry.gitlab.com/tigefa/ffmpeg"
  cpu: 8
  memory: 21

ffmpeg_task:
  timeout_in: 120m
  install_script:
    - apt-get update
    - apt-get dist-upgrade -yqq
    - apt-get install -yqq sudo lsb-base lsb-release apt-transport-https ca-certificates software-properties-common wget curl netcat aria2 whois figlet p7zip p7zip-full zip unzip
    - apt-get install -yqq wget aria2 ffmpeg telnet tree lshw
  test_script:
    - aria2c --bt-seed-unverified=true --seed-time=1 --seed-ratio=1.0 "https://yts.mx/torrent/download/F139C39FD3D1A94CC980BD863659EA225A0AAA4A"
#    - "aria2c --check-certificate=false --header 'Host: nl22.seedr.cc' --user-agent 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:79.0) Gecko/20100101 Firefox/79.0' --header 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8' --header 'Accept-Language: id,en-US;q=0.7,en;q=0.3' --header 'Proxy-Authorization: Basic dGlnZWZhQGdtYWlsLmNvbTpxS29xUmZ5SFBwdXBlcXRFNHNQYg==' --referer 'https://www.seedr.cc/files/140356248' --header 'Upgrade-Insecure-Requests: 1' 'https://nl22.seedr.cc/ff_get/728051072/PPPD-866.mp4?st=MLG9mPImVQ1PkHan13R-Jw&e=1597960088' --out 'PPPD-866.mp4'"
    - ffmpeg -i "Ava (2020) [720p] [WEBRip] [YTS.MX]/Ava.2020.720p.WEBRip.x264.AAC-[YTS.MX].mp4" -threads 16 -c:v libx265 -c:a copy -metadata title="Ava 2020" -preset veryfast Ava.2020.720p.WEBRip.x265.mp4
    - ls -hal
  binaries_artifacts:
    path: "Ava.2020.720p.WEBRip.x265.mp4"
